### ISSUE TITLE
Distinguish public and private 

### ISSUE THREAD

**Issue by tigercosmos** [nycu-sslab/repo-navigator#1]
This repo is public, so people can access the content of this repo.
However, the links in the repo are all private, leading to the result that people actually can read nothing here.
cc @ypyou

**Comment by ypyou** [comment]
This repo is made public intentionally so that it can be pinned for easy access. Do you suggest a better way to do this?

**Comment by tigercosmos** [comment]
I think we can put public resources on top of the repo, such as open-source projects or publications, and leave the private things in the end (mention internal purpose link).

**Comment by ypyou** [comment]
Suggestion taken.

**Comment by tigercosmos** [comment]
https://github.com/nycu-sslab/private_navigator/blob/master/open-source.md
this is still in a private repo.

**Comment by ypyou** [comment]
Should be fixed now.
